plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.141.59'
    //implementation 'org.seleniumhq.selenium:selenium-java:4.12.0'
    testImplementation group: 'org.testng', name: 'testng', version: '7.10.2'
    implementation group: 'net.coobird', name: 'thumbnailator', version: '0.4.19'
    implementation group: 'com.itextpdf', name: 'itextpdf', version: '5.5.13.3'
    // Agregar Selenium (ajusta la versión según tu necesidad)






}

test {

   useTestNG()
}